execute pathogen#infect()
syntax on
filetype plugin indent on 

let g:NERDTreeWinPos="right"
set splitright
colo brighton
set number
set ruler 
set cursorline
set si
set smarttab



set tabstop=4
set shiftwidth=2
set shiftround
set expandtab
set tabstop=4
set softtabstop=4

set shiftround
set showmatch 

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

map <space> /
map <c-sapce> ?
